{{- if and .Values.initContainers.enabled .Values.initContainers.dataInjector.enabled .Values.initContainers.dataInjector.source.autoGenerateSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.initContainers.dataInjector.source.secretName }}
type: Opaque
data:
  S3_HOSTNAME: {{ default "" .Values.initContainers.dataInjector.source.s3.hostname | b64enc | quote }}
  S3_ACCESS_KEY: {{ default "" .Values.initContainers.dataInjector.source.s3.accessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ default "" .Values.initContainers.dataInjector.source.s3.secretKey | b64enc | quote }}
  S3_BUCKET: {{ default "" .Values.initContainers.dataInjector.source.s3.bucket | b64enc | quote }}
  S3_FILENAME: {{ default "" .Values.initContainers.dataInjector.source.s3.filename | b64enc | quote }}
{{- end}}