apiVersion: v2
name: hyperflow
description: Umbrella chart for Hyperflow WMS and workflow deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    repository: file://../redis
    version: 0.*
  - name: nfs-server-provisioner
    repository: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner
    version: 1.6.*
  - name: nfs-volume
    repository: file://../nfs-volume
    version: 0.*
  - name: hyperflow-engine
    repository: file://../hyperflow-engine
    version: 0.*
  - name: hyperflow-worker-pool-operator
    repository: file://../hyperflow-worker-pool-operator
    version: 0.*
    condition: worker-pools.enabled
  - name: hyperflow-nfs-data
    repository: file://../hyperflow-nfs-data
    version: 0.*

