apiVersion: v1
{{- with .Values.config.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
kind: ConfigMap
metadata:
  name: hyperflow-worker-pool-operator-templates
  namespace: {{ .Release.Namespace }}
