---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: hyperflow-worker-pool-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperflow-worker-pool-operator-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [ "" ]
    resources: [ events ]
    verbs: [ create ]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [ hyperflow.agh.edu.pl ]
    resources: [ workerpools ]
    verbs: [ get, list, watch, patch ]
  - apiGroups: ["apps"]
    resources: [deployments]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: ["monitoring.coreos.com"]
    resources: [prometheusrules]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: ["keda.sh"]
    resources: [scaledobjects]
    verbs: [get, list, watch, patch, create, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: hyperflow-worker-pool-operator-role-namespaced
rules:

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [ hyperflow.agh.edu.pl ]
    resources: [ workerpools ]
    verbs: [ get, list, watch, patch ]
  - apiGroups: ["apps"]
    resources: [deployments]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: ["monitoring.coreos.com"]
    resources: [prometheusrules]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: ["keda.sh"]
    resources: [scaledobjects]
    verbs: [get, list, watch, patch, create, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hyperflow-worker-pool-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hyperflow-worker-pool-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: hyperflow-worker-pool-operator-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: hyperflow-worker-pool-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hyperflow-worker-pool-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: hyperflow-worker-pool-operator-account
