apiVersion: v2
name: hyperflow-run
description: Umbrella chart for running a HyperFlow workflow
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    repository: file://../redis
    version: 0.*
  - name: nfs-volume
    repository: file://../nfs-volume
    version: 0.*
  - name: hyperflow-engine
    repository: file://../hyperflow-engine
    version: 0.*
  - name: hyperflow-nfs-data
    repository: file://../hyperflow-nfs-data
    version: 0.*
    condition: hyperflow-nfs-data.enabled

