apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hyperflow
      name: redis
  template:
    metadata:
      labels:
        app: hyperflow
        name: redis
    spec:
      containers:
        - image: {{ .Values.image }}
          name: redis
          ports:
            - containerPort: {{ .Values.container.port }}
              name: redis
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8}}
      {{- end }}