apiVersion: v2
name: hyperflow-operations
description: Umbrella chart for deployment of Hyperflow WMS infrastructure services
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: nfs-server-provisioner
    repository: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner
    version: 1.6.*
  - name: hyperflow-worker-pool-operator
    repository: file://../hyperflow-worker-pool-operator
    version: 0.*
    condition: worker-pools.enabled
