apiVersion: v2
appVersion: 1.0.0
dependencies:
- condition: kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 68.*.*
- condition: prometheus-adapter.enabled
  name: prometheus-adapter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.11.*
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 15.2.*
- condition: prometheus-rabbitmq-exporter.enabled
  name: prometheus-rabbitmq-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 1.13.*
- condition: keda.enabled
  name: keda
  repository: https://kedacore.github.io/charts
  version: 2.16.*
description: A Helm chart for Hyperflow Worker Pools operator
name: hyperflow-worker-pool-operator
type: application
version: 0.2.0
